### PR TITLE
feat(types): add typescript typings

### LINKED ISSUE #19: TypeScript support?
Hello,

any TypeScript support planned for this plugin?

### PR DESCRIPTION
**Pull request by SkeLLLa**
Adds typescript support.
Closes #19

### CODE REVIEW

**Comment by cemremengu** [comment]
cc @delvedor @evanshortiss @mcollina

**Comment by SkeLLLa** [comment]
@cemremengu yep.

**Comment by karlos1337** [comment]
@cemremengu  @mcollina  @delvedor News about this?

**Comment by karlos1337** [comment]
@cemremengu @mcollina @delvedor News about this?

**Pull request merged**
